// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: insurance/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetNextRecRequest struct {
}

func (m *QueryGetNextRecRequest) Reset()         { *m = QueryGetNextRecRequest{} }
func (m *QueryGetNextRecRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNextRecRequest) ProtoMessage()    {}
func (*QueryGetNextRecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{2}
}
func (m *QueryGetNextRecRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNextRecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNextRecRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNextRecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNextRecRequest.Merge(m, src)
}
func (m *QueryGetNextRecRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNextRecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNextRecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNextRecRequest proto.InternalMessageInfo

type QueryGetNextRecResponse struct {
	NextRec NextRec `protobuf:"bytes,1,opt,name=NextRec,proto3" json:"NextRec"`
}

func (m *QueryGetNextRecResponse) Reset()         { *m = QueryGetNextRecResponse{} }
func (m *QueryGetNextRecResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNextRecResponse) ProtoMessage()    {}
func (*QueryGetNextRecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{3}
}
func (m *QueryGetNextRecResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNextRecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNextRecResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNextRecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNextRecResponse.Merge(m, src)
}
func (m *QueryGetNextRecResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNextRecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNextRecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNextRecResponse proto.InternalMessageInfo

func (m *QueryGetNextRecResponse) GetNextRec() NextRec {
	if m != nil {
		return m.NextRec
	}
	return NextRec{}
}

type QueryGetCrashRecRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCrashRecRequest) Reset()         { *m = QueryGetCrashRecRequest{} }
func (m *QueryGetCrashRecRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCrashRecRequest) ProtoMessage()    {}
func (*QueryGetCrashRecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{4}
}
func (m *QueryGetCrashRecRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCrashRecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCrashRecRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCrashRecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCrashRecRequest.Merge(m, src)
}
func (m *QueryGetCrashRecRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCrashRecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCrashRecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCrashRecRequest proto.InternalMessageInfo

func (m *QueryGetCrashRecRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCrashRecResponse struct {
	CrashRec CrashRec `protobuf:"bytes,1,opt,name=crashRec,proto3" json:"crashRec"`
}

func (m *QueryGetCrashRecResponse) Reset()         { *m = QueryGetCrashRecResponse{} }
func (m *QueryGetCrashRecResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCrashRecResponse) ProtoMessage()    {}
func (*QueryGetCrashRecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{5}
}
func (m *QueryGetCrashRecResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCrashRecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCrashRecResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCrashRecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCrashRecResponse.Merge(m, src)
}
func (m *QueryGetCrashRecResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCrashRecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCrashRecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCrashRecResponse proto.InternalMessageInfo

func (m *QueryGetCrashRecResponse) GetCrashRec() CrashRec {
	if m != nil {
		return m.CrashRec
	}
	return CrashRec{}
}

type QueryAllCrashRecRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCrashRecRequest) Reset()         { *m = QueryAllCrashRecRequest{} }
func (m *QueryAllCrashRecRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCrashRecRequest) ProtoMessage()    {}
func (*QueryAllCrashRecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{6}
}
func (m *QueryAllCrashRecRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCrashRecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCrashRecRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCrashRecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCrashRecRequest.Merge(m, src)
}
func (m *QueryAllCrashRecRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCrashRecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCrashRecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCrashRecRequest proto.InternalMessageInfo

func (m *QueryAllCrashRecRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCrashRecResponse struct {
	CrashRec   []CrashRec          `protobuf:"bytes,1,rep,name=crashRec,proto3" json:"crashRec"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCrashRecResponse) Reset()         { *m = QueryAllCrashRecResponse{} }
func (m *QueryAllCrashRecResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCrashRecResponse) ProtoMessage()    {}
func (*QueryAllCrashRecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe1143045b4fb1c, []int{7}
}
func (m *QueryAllCrashRecResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCrashRecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCrashRecResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCrashRecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCrashRecResponse.Merge(m, src)
}
func (m *QueryAllCrashRecResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCrashRecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCrashRecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCrashRecResponse proto.InternalMessageInfo

func (m *QueryAllCrashRecResponse) GetCrashRec() []CrashRec {
	if m != nil {
		return m.CrashRec
	}
	return nil
}

func (m *QueryAllCrashRecResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "denischerkasskikh.insurance.insurance.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "denischerkasskikh.insurance.insurance.QueryParamsResponse")
	proto.RegisterType((*QueryGetNextRecRequest)(nil), "denischerkasskikh.insurance.insurance.QueryGetNextRecRequest")
	proto.RegisterType((*QueryGetNextRecResponse)(nil), "denischerkasskikh.insurance.insurance.QueryGetNextRecResponse")
	proto.RegisterType((*QueryGetCrashRecRequest)(nil), "denischerkasskikh.insurance.insurance.QueryGetCrashRecRequest")
	proto.RegisterType((*QueryGetCrashRecResponse)(nil), "denischerkasskikh.insurance.insurance.QueryGetCrashRecResponse")
	proto.RegisterType((*QueryAllCrashRecRequest)(nil), "denischerkasskikh.insurance.insurance.QueryAllCrashRecRequest")
	proto.RegisterType((*QueryAllCrashRecResponse)(nil), "denischerkasskikh.insurance.insurance.QueryAllCrashRecResponse")
}

func init() { proto.RegisterFile("insurance/query.proto", fileDescriptor_ffe1143045b4fb1c) }

var fileDescriptor_ffe1143045b4fb1c = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6b, 0x13, 0x41,
	0x18, 0xc7, 0x33, 0xd5, 0xc6, 0x3a, 0xbd, 0x8d, 0xb1, 0xc6, 0x20, 0xab, 0x2c, 0xf8, 0x82, 0xd0,
	0x19, 0x13, 0x11, 0x63, 0xc1, 0x97, 0xb6, 0x62, 0x0f, 0x42, 0x69, 0xf7, 0xe8, 0x45, 0x26, 0xdb,
	0x61, 0xb3, 0x24, 0x99, 0xd9, 0xee, 0x4c, 0x24, 0x45, 0xbc, 0xf8, 0x09, 0x04, 0x3f, 0x80, 0xdf,
	0xa2, 0x77, 0x6f, 0xb9, 0x08, 0x05, 0x2f, 0x9e, 0x44, 0x12, 0x3f, 0x88, 0x64, 0xf6, 0xd9, 0x6c,
	0x5e, 0x8a, 0x6e, 0x82, 0xb7, 0xc9, 0xcc, 0x3c, 0xff, 0xff, 0xef, 0xbf, 0x79, 0x9e, 0x5d, 0x7c,
	0x35, 0x94, 0xba, 0x1b, 0x73, 0xe9, 0x0b, 0x76, 0xdc, 0x15, 0xf1, 0x09, 0x8d, 0x62, 0x65, 0x14,
	0xb9, 0x7d, 0x24, 0x64, 0xa8, 0xfd, 0xa6, 0x88, 0x5b, 0x5c, 0xeb, 0x56, 0xd8, 0x6a, 0xd2, 0xf1,
	0xc5, 0x6c, 0x55, 0x29, 0x05, 0x2a, 0x50, 0xb6, 0x82, 0x8d, 0x56, 0x49, 0x71, 0xe5, 0x46, 0xa0,
	0x54, 0xd0, 0x16, 0x8c, 0x47, 0x21, 0xe3, 0x52, 0x2a, 0xc3, 0x4d, 0xa8, 0xa4, 0x86, 0xd3, 0xfb,
	0xbe, 0xd2, 0x1d, 0xa5, 0x59, 0x83, 0x6b, 0xf0, 0x64, 0xef, 0xaa, 0x0d, 0x61, 0x78, 0x95, 0x45,
	0x3c, 0x08, 0xa5, 0xbd, 0x0c, 0x77, 0x37, 0x32, 0xba, 0x88, 0xc7, 0xbc, 0x93, 0x6a, 0x94, 0xb3,
	0x7d, 0x29, 0x7a, 0xe6, 0x6d, 0x2c, 0x7c, 0x38, 0xb9, 0x9e, 0x9d, 0xf8, 0x31, 0xd7, 0xcd, 0xec,
	0xc8, 0x2d, 0x61, 0x72, 0x38, 0xb2, 0x3b, 0xb0, 0x4a, 0x9e, 0x38, 0xee, 0x0a, 0x6d, 0xdc, 0x06,
	0xbe, 0x32, 0xb5, 0xab, 0x23, 0x25, 0xb5, 0x20, 0xaf, 0x71, 0x31, 0x71, 0x2c, 0xa3, 0x5b, 0xe8,
	0xde, 0x7a, 0x6d, 0x93, 0xe6, 0x7a, 0x22, 0x34, 0x91, 0xd9, 0xb9, 0xd8, 0xff, 0x79, 0xb3, 0xe0,
	0x81, 0x84, 0x5b, 0xc6, 0x1b, 0xd6, 0x63, 0x4f, 0x98, 0x7d, 0xd1, 0x33, 0x9e, 0xf0, 0x53, 0xf7,
	0x10, 0x5f, 0x9b, 0x3b, 0x01, 0x82, 0x7d, 0x7c, 0x09, 0xb6, 0x00, 0x81, 0xe6, 0x44, 0x80, 0x2a,
	0x60, 0x48, 0x45, 0x5c, 0x96, 0x59, 0xed, 0x8e, 0x9e, 0x4c, 0x46, 0x41, 0x4a, 0x78, 0x35, 0x94,
	0x47, 0xa2, 0x67, 0x8d, 0x2e, 0x7b, 0xc9, 0x0f, 0xb7, 0x83, 0xcb, 0xf3, 0x05, 0x00, 0x77, 0x88,
	0xd7, 0x7c, 0xd8, 0x03, 0x3a, 0x96, 0x93, 0x2e, 0x95, 0x02, 0xbc, 0xb1, 0x8c, 0xcb, 0x81, 0x6f,
	0xbb, 0xdd, 0x9e, 0xe5, 0x7b, 0x85, 0x71, 0xd6, 0x1a, 0xe0, 0x77, 0x87, 0x26, 0x7d, 0x44, 0x47,
	0x7d, 0x44, 0x93, 0xde, 0x85, 0x3e, 0xa2, 0x07, 0x3c, 0x10, 0x50, 0xeb, 0x4d, 0x54, 0xba, 0xa7,
	0x08, 0x22, 0x4d, 0x79, 0x9c, 0x1b, 0xe9, 0xc2, 0x7f, 0x88, 0x44, 0xf6, 0xa6, 0xb8, 0x57, 0x2c,
	0xf7, 0xdd, 0x7f, 0x72, 0x27, 0x3c, 0x93, 0xe0, 0xb5, 0x2f, 0x45, 0xbc, 0x6a, 0xc1, 0xc9, 0x29,
	0xc2, 0xc5, 0xa4, 0xc7, 0xc8, 0x93, 0x9c, 0x78, 0xf3, 0x4d, 0x5f, 0xd9, 0x5a, 0xa6, 0x34, 0xe1,
	0x72, 0x1f, 0x7d, 0xfc, 0xfe, 0xfb, 0xf3, 0x0a, 0x23, 0x9b, 0xec, 0xe5, 0x48, 0x63, 0x77, 0x42,
	0x83, 0x65, 0xc3, 0x37, 0x3b, 0xb8, 0xe4, 0x2b, 0x1a, 0xf7, 0x33, 0x79, 0xba, 0x88, 0xfd, 0xdc,
	0xd0, 0x54, 0x9e, 0x2d, 0x5b, 0x0e, 0x09, 0x1e, 0xdb, 0x04, 0x55, 0xc2, 0x72, 0x26, 0x48, 0x5f,
	0x31, 0xe4, 0x1b, 0xc2, 0x6b, 0xe9, 0x9f, 0x4d, 0x16, 0xa5, 0x98, 0x69, 0xea, 0xca, 0xf3, 0xa5,
	0xeb, 0x21, 0xc6, 0x0b, 0x1b, 0x63, 0x8b, 0xd4, 0x73, 0xc6, 0x18, 0xbf, 0x0f, 0xd9, 0x7b, 0x3b,
	0xe0, 0x1f, 0x48, 0x1f, 0xe1, 0xf5, 0x54, 0x76, 0xbb, 0xdd, 0x5e, 0x2c, 0xd2, 0xfc, 0x9c, 0x2e,
	0x16, 0xe9, 0x9c, 0x19, 0x74, 0xeb, 0x36, 0x52, 0x8d, 0x3c, 0x58, 0x34, 0xd2, 0x8e, 0xd7, 0x1f,
	0x38, 0xe8, 0x6c, 0xe0, 0xa0, 0x5f, 0x03, 0x07, 0x7d, 0x1a, 0x3a, 0x85, 0xb3, 0xa1, 0x53, 0xf8,
	0x31, 0x74, 0x0a, 0x6f, 0xea, 0x41, 0x68, 0x9a, 0xdd, 0x06, 0xf5, 0x55, 0xe7, 0xaf, 0xaa, 0xbd,
	0x89, 0xb5, 0x39, 0x89, 0x84, 0x6e, 0x14, 0xed, 0x77, 0xe3, 0xe1, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa8, 0x2b, 0x65, 0xfe, 0x24, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a NextRec by index.
	NextRec(ctx context.Context, in *QueryGetNextRecRequest, opts ...grpc.CallOption) (*QueryGetNextRecResponse, error)
	// Queries a CrashRec by index.
	CrashRec(ctx context.Context, in *QueryGetCrashRecRequest, opts ...grpc.CallOption) (*QueryGetCrashRecResponse, error)
	// Queries a list of CrashRec items.
	CrashRecAll(ctx context.Context, in *QueryAllCrashRecRequest, opts ...grpc.CallOption) (*QueryAllCrashRecResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/denischerkasskikh.insurance.insurance.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NextRec(ctx context.Context, in *QueryGetNextRecRequest, opts ...grpc.CallOption) (*QueryGetNextRecResponse, error) {
	out := new(QueryGetNextRecResponse)
	err := c.cc.Invoke(ctx, "/denischerkasskikh.insurance.insurance.Query/NextRec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CrashRec(ctx context.Context, in *QueryGetCrashRecRequest, opts ...grpc.CallOption) (*QueryGetCrashRecResponse, error) {
	out := new(QueryGetCrashRecResponse)
	err := c.cc.Invoke(ctx, "/denischerkasskikh.insurance.insurance.Query/CrashRec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CrashRecAll(ctx context.Context, in *QueryAllCrashRecRequest, opts ...grpc.CallOption) (*QueryAllCrashRecResponse, error) {
	out := new(QueryAllCrashRecResponse)
	err := c.cc.Invoke(ctx, "/denischerkasskikh.insurance.insurance.Query/CrashRecAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a NextRec by index.
	NextRec(context.Context, *QueryGetNextRecRequest) (*QueryGetNextRecResponse, error)
	// Queries a CrashRec by index.
	CrashRec(context.Context, *QueryGetCrashRecRequest) (*QueryGetCrashRecResponse, error)
	// Queries a list of CrashRec items.
	CrashRecAll(context.Context, *QueryAllCrashRecRequest) (*QueryAllCrashRecResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) NextRec(ctx context.Context, req *QueryGetNextRecRequest) (*QueryGetNextRecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextRec not implemented")
}
func (*UnimplementedQueryServer) CrashRec(ctx context.Context, req *QueryGetCrashRecRequest) (*QueryGetCrashRecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrashRec not implemented")
}
func (*UnimplementedQueryServer) CrashRecAll(ctx context.Context, req *QueryAllCrashRecRequest) (*QueryAllCrashRecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrashRecAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/denischerkasskikh.insurance.insurance.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NextRec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNextRecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NextRec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/denischerkasskikh.insurance.insurance.Query/NextRec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NextRec(ctx, req.(*QueryGetNextRecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CrashRec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCrashRecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CrashRec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/denischerkasskikh.insurance.insurance.Query/CrashRec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CrashRec(ctx, req.(*QueryGetCrashRecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CrashRecAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCrashRecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CrashRecAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/denischerkasskikh.insurance.insurance.Query/CrashRecAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CrashRecAll(ctx, req.(*QueryAllCrashRecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "denischerkasskikh.insurance.insurance.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "NextRec",
			Handler:    _Query_NextRec_Handler,
		},
		{
			MethodName: "CrashRec",
			Handler:    _Query_CrashRec_Handler,
		},
		{
			MethodName: "CrashRecAll",
			Handler:    _Query_CrashRecAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "insurance/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNextRecRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNextRecRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNextRecRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetNextRecResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNextRecResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNextRecResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NextRec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCrashRecRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCrashRecRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCrashRecRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCrashRecResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCrashRecResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCrashRecResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CrashRec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCrashRecRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCrashRecRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCrashRecRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCrashRecResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCrashRecResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCrashRecResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CrashRec) > 0 {
		for iNdEx := len(m.CrashRec) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CrashRec[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNextRecRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetNextRecResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NextRec.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCrashRecRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCrashRecResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CrashRec.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCrashRecRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCrashRecResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CrashRec) > 0 {
		for _, e := range m.CrashRec {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNextRecRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNextRecRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNextRecRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNextRecResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNextRecResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNextRecResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextRec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NextRec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCrashRecRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCrashRecRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCrashRecRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCrashRecResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCrashRecResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCrashRecResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrashRec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CrashRec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCrashRecRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCrashRecRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCrashRecRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCrashRecResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCrashRecResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCrashRecResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrashRec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CrashRec = append(m.CrashRec, CrashRec{})
			if err := m.CrashRec[len(m.CrashRec)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
