// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: insurance/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAddRecord struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Brand        string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model        string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year         string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Owner        string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	LicensePlate string `protobuf:"bytes,6,opt,name=licensePlate,proto3" json:"licensePlate,omitempty"`
	VinNumber    string `protobuf:"bytes,7,opt,name=vinNumber,proto3" json:"vinNumber,omitempty"`
	Odometer     string `protobuf:"bytes,8,opt,name=odometer,proto3" json:"odometer,omitempty"`
	Side         string `protobuf:"bytes,9,opt,name=side,proto3" json:"side,omitempty"`
	Part         string `protobuf:"bytes,10,opt,name=part,proto3" json:"part,omitempty"`
	Payout       string `protobuf:"bytes,11,opt,name=payout,proto3" json:"payout,omitempty"`
}

func (m *MsgAddRecord) Reset()         { *m = MsgAddRecord{} }
func (m *MsgAddRecord) String() string { return proto.CompactTextString(m) }
func (*MsgAddRecord) ProtoMessage()    {}
func (*MsgAddRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_71f4fc5d8a3c391e, []int{0}
}
func (m *MsgAddRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRecord.Merge(m, src)
}
func (m *MsgAddRecord) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRecord proto.InternalMessageInfo

func (m *MsgAddRecord) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddRecord) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *MsgAddRecord) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MsgAddRecord) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *MsgAddRecord) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgAddRecord) GetLicensePlate() string {
	if m != nil {
		return m.LicensePlate
	}
	return ""
}

func (m *MsgAddRecord) GetVinNumber() string {
	if m != nil {
		return m.VinNumber
	}
	return ""
}

func (m *MsgAddRecord) GetOdometer() string {
	if m != nil {
		return m.Odometer
	}
	return ""
}

func (m *MsgAddRecord) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *MsgAddRecord) GetPart() string {
	if m != nil {
		return m.Part
	}
	return ""
}

func (m *MsgAddRecord) GetPayout() string {
	if m != nil {
		return m.Payout
	}
	return ""
}

type MsgAddRecordResponse struct {
	RecNum string `protobuf:"bytes,1,opt,name=recNum,proto3" json:"recNum,omitempty"`
}

func (m *MsgAddRecordResponse) Reset()         { *m = MsgAddRecordResponse{} }
func (m *MsgAddRecordResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddRecordResponse) ProtoMessage()    {}
func (*MsgAddRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71f4fc5d8a3c391e, []int{1}
}
func (m *MsgAddRecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddRecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRecordResponse.Merge(m, src)
}
func (m *MsgAddRecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRecordResponse proto.InternalMessageInfo

func (m *MsgAddRecordResponse) GetRecNum() string {
	if m != nil {
		return m.RecNum
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAddRecord)(nil), "denischerkasskikh.insurance.insurance.MsgAddRecord")
	proto.RegisterType((*MsgAddRecordResponse)(nil), "denischerkasskikh.insurance.insurance.MsgAddRecordResponse")
}

func init() { proto.RegisterFile("insurance/tx.proto", fileDescriptor_71f4fc5d8a3c391e) }

var fileDescriptor_71f4fc5d8a3c391e = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0xc6, 0xe3, 0xfc, 0xb7, 0x9a, 0x49, 0x84, 0x22, 0x42, 0x31, 0x25, 0x50, 0xe8, 0xe4, 0x40,
	0xb3, 0x14, 0x3a, 0xf5, 0xcf, 0x9a, 0x50, 0x3c, 0x76, 0x93, 0xad, 0x23, 0x11, 0x89, 0x25, 0x23,
	0xc9, 0x6d, 0x32, 0x74, 0xeb, 0x03, 0xf4, 0x01, 0xfa, 0x40, 0x1d, 0x33, 0x76, 0x2c, 0xc9, 0x8b,
	0x14, 0xc9, 0x49, 0xec, 0x6e, 0xa5, 0xdb, 0xf7, 0xfd, 0xee, 0x13, 0x77, 0x9c, 0x0e, 0x61, 0x2e,
	0x74, 0xae, 0xa8, 0x48, 0x60, 0x64, 0x56, 0x61, 0xa6, 0xa4, 0x91, 0xf8, 0x82, 0x81, 0xe0, 0x3a,
	0x99, 0x83, 0x5a, 0x50, 0xad, 0x17, 0x7c, 0x31, 0x0f, 0x8f, 0xa9, 0x52, 0x0d, 0x3f, 0xea, 0xa8,
	0x37, 0xd1, 0xb3, 0x5b, 0xc6, 0x22, 0x48, 0xa4, 0x62, 0x98, 0xa0, 0x4e, 0xa2, 0x80, 0x1a, 0xa9,
	0x88, 0x77, 0xee, 0x5d, 0xfa, 0xd1, 0xc1, 0xe2, 0x3e, 0x6a, 0xc5, 0x8a, 0x0a, 0x46, 0xea, 0x8e,
	0x17, 0xc6, 0xd2, 0x54, 0x32, 0x58, 0x92, 0x46, 0x41, 0x9d, 0xc1, 0x18, 0x35, 0xd7, 0x40, 0x15,
	0x69, 0x3a, 0xe8, 0xb4, 0x4d, 0xca, 0x17, 0x01, 0x8a, 0xb4, 0x8a, 0xa4, 0x33, 0x78, 0x88, 0x7a,
	0x4b, 0x9e, 0x80, 0xd0, 0xf0, 0xb8, 0xa4, 0x06, 0x48, 0xdb, 0x15, 0x7f, 0x31, 0x7c, 0x86, 0xfc,
	0x67, 0x2e, 0xa6, 0x79, 0x1a, 0x83, 0x22, 0x1d, 0x17, 0x28, 0x01, 0x1e, 0xa0, 0xae, 0x64, 0x32,
	0x05, 0x03, 0x8a, 0x74, 0x5d, 0xf1, 0xe8, 0xed, 0x1c, 0x9a, 0x33, 0x20, 0x7e, 0x31, 0x87, 0xd5,
	0x96, 0x65, 0x54, 0x19, 0x82, 0x0a, 0x66, 0x35, 0x3e, 0x45, 0xed, 0x8c, 0xae, 0x65, 0x6e, 0xc8,
	0x89, 0xa3, 0x7b, 0x37, 0x0c, 0x51, 0xbf, 0xba, 0x9d, 0x08, 0x74, 0x26, 0x85, 0x06, 0x9b, 0x57,
	0x90, 0x4c, 0xf3, 0x74, 0xbf, 0xa4, 0xbd, 0xbb, 0x7a, 0xf3, 0x50, 0x63, 0xa2, 0x67, 0xf8, 0x15,
	0xf9, 0xe5, 0x4a, 0xc7, 0xe1, 0x9f, 0xfe, 0x22, 0xac, 0x76, 0x1a, 0xdc, 0xfc, 0xe3, 0xd1, 0x61,
	0xbc, 0xbb, 0xe8, 0x73, 0x1b, 0x78, 0x9b, 0x6d, 0xe0, 0x7d, 0x6f, 0x03, 0xef, 0x7d, 0x17, 0xd4,
	0x36, 0xbb, 0xa0, 0xf6, 0xb5, 0x0b, 0x6a, 0x4f, 0xd7, 0x33, 0x6e, 0xe6, 0x79, 0x1c, 0x26, 0x32,
	0x1d, 0x3d, 0xd8, 0x06, 0xf7, 0x95, 0x06, 0xa3, 0xf2, 0x8e, 0x56, 0x15, 0x6d, 0xd6, 0x19, 0xe8,
	0xb8, 0xed, 0xee, 0x6a, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x88, 0x84, 0xbc, 0x6d, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AddRecord(ctx context.Context, in *MsgAddRecord, opts ...grpc.CallOption) (*MsgAddRecordResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddRecord(ctx context.Context, in *MsgAddRecord, opts ...grpc.CallOption) (*MsgAddRecordResponse, error) {
	out := new(MsgAddRecordResponse)
	err := c.cc.Invoke(ctx, "/denischerkasskikh.insurance.insurance.Msg/AddRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AddRecord(context.Context, *MsgAddRecord) (*MsgAddRecordResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddRecord(ctx context.Context, req *MsgAddRecord) (*MsgAddRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecord not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/denischerkasskikh.insurance.insurance.Msg/AddRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddRecord(ctx, req.(*MsgAddRecord))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "denischerkasskikh.insurance.insurance.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _Msg_AddRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "insurance/tx.proto",
}

func (m *MsgAddRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payout) > 0 {
		i -= len(m.Payout)
		copy(dAtA[i:], m.Payout)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payout)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Part) > 0 {
		i -= len(m.Part)
		copy(dAtA[i:], m.Part)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Part)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Side) > 0 {
		i -= len(m.Side)
		copy(dAtA[i:], m.Side)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Side)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Odometer) > 0 {
		i -= len(m.Odometer)
		copy(dAtA[i:], m.Odometer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Odometer)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.VinNumber) > 0 {
		i -= len(m.VinNumber)
		copy(dAtA[i:], m.VinNumber)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VinNumber)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.LicensePlate) > 0 {
		i -= len(m.LicensePlate)
		copy(dAtA[i:], m.LicensePlate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LicensePlate)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Year) > 0 {
		i -= len(m.Year)
		copy(dAtA[i:], m.Year)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Year)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Model) > 0 {
		i -= len(m.Model)
		copy(dAtA[i:], m.Model)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Model)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Brand) > 0 {
		i -= len(m.Brand)
		copy(dAtA[i:], m.Brand)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Brand)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddRecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddRecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddRecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecNum) > 0 {
		i -= len(m.RecNum)
		copy(dAtA[i:], m.RecNum)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RecNum)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Brand)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Year)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LicensePlate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VinNumber)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Odometer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Side)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Part)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payout)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddRecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecNum)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Brand", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Brand = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Year", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Year = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LicensePlate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LicensePlate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VinNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VinNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Odometer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Odometer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Side = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Part", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Part = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payout = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddRecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddRecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddRecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecNum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecNum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
